language: rust
cache: cargo
rust:
  - 1.15.0
  - 1.16.0
  - 1.17.0
  - 1.18.0
  - 1.19.0
  - stable
  - beta
  - nightly
script:
  - cargo build --verbose
  - cargo test --verbose
matrix:
  allow_failures:
    - rust: nightly
