[package]
name = "slurp"
version = "1.0.0"
authors = ["QuietMisdreavus <grey@quietmisdreavus.net>"]
repository = "https://github.com/QuietMisdreavus/slurp"
categories = ["filesystem"]
license = "Unlicense"
readme = "README.md"

[dependencies]
